FLAGS = -g
JC = javac
JVM= java 

.SUFFIXES: .java .class
.java.class:
        $(JC) $(JFLAGS) $*.java

CLASSES = \
        Dijkstra.java \
        DijkstraMethod.java \
        Method.java \
        Graph.java \
        FibonacciHeap.java \
        LeftistHeapNode.java

MAIN = Dijkstra

default: classes

classes: $(CLASSES:.java=.class)

run: $(MAIN).class
	$(JVM) $(MAIN)
clean:
        $(RM) *.class